
import { FiscalYear, FundingSource, ProjectStatus, ResearchCategory, PublicationLevel, PublicationType, OrganizationType, Organization, UtilizationType, DevelopmentType, IPType } from "./types";

export const FISCAL_YEARS = Object.values(FiscalYear);
export const FUNDING_SOURCES = Object.values(FundingSource);
export const PROJECT_STATUSES = Object.values(ProjectStatus);
export const RESEARCH_CATEGORIES = Object.values(ResearchCategory);
export const PUBLICATION_LEVELS = Object.values(PublicationLevel);
export const PUBLICATION_TYPES = Object.values(PublicationType);
export const UTILIZATION_TYPES = Object.values(UtilizationType);
export const DEVELOPMENT_TYPES = Object.values(DevelopmentType);
export const IP_TYPES = Object.values(IPType);

// --- ORGANIZATIONS DATA ---

export const CENTRAL_OFFICE: Organization[] = [
  { id: "c_office", nameEn: "Office of the President", nameTh: "สำนักงานอธิการบดี", type: OrganizationType.OfficePresident }
];

export const CAMPUSES: Organization[] = [
  { id: "c_chiangmai", nameEn: "Chiang Mai Campus", nameTh: "วิทยาเขตเชียงใหม่", type: OrganizationType.Campus },
  { id: "c_phetchabun", nameEn: "Phetchabun Campus", nameTh: "วิทยาเขตเพชรบูรณ์", type: OrganizationType.Campus },
  { id: "c_lampang", nameEn: "Lampang Campus", nameTh: "วิทยาเขตลำปาง", type: OrganizationType.Campus },
  { id: "c_sukhothai", nameEn: "Sukhothai Campus", nameTh: "วิทยาเขตสุโขทัย", type: OrganizationType.Campus },
  { id: "c_bangkok", nameEn: "Bangkok Campus", nameTh: "วิทยาเขตกรุงเทพ", type: OrganizationType.Campus },
  { id: "c_chonburi", nameEn: "Chonburi Campus", nameTh: "วิทยาเขตชลบุรี", type: OrganizationType.Campus },
  { id: "c_samutsakhon", nameEn: "Samut Sakhon Campus", nameTh: "วิทยาเขตสมุทรสาคร", type: OrganizationType.Campus },
  { id: "c_suphanburi", nameEn: "Suphan Buri Campus", nameTh: "วิทยาเขตสุพรรณบุรี", type: OrganizationType.Campus },
  { id: "c_angthong", nameEn: "Ang Thong Campus", nameTh: "วิทยาเขตอ่างทอง", type: OrganizationType.Campus },
  { id: "c_chaiyaphum", nameEn: "Chaiyaphum Campus", nameTh: "วิทยาเขตชัยภูมิ", type: OrganizationType.Campus },
  { id: "c_mahasarakham", nameEn: "Maha Sarakham Campus", nameTh: "วิทยาเขตมหาสารคาม", type: OrganizationType.Campus },
  { id: "c_sisaket", nameEn: "Sisaket Campus", nameTh: "วิทยาเขตศรีสะเกษ", type: OrganizationType.Campus },
  { id: "c_udonthani", nameEn: "Udon Thani Campus", nameTh: "วิทยาเขตอุดรธานี", type: OrganizationType.Campus },
  { id: "c_krabi", nameEn: "Krabi Campus", nameTh: "วิทยาเขตกระบี่", type: OrganizationType.Campus },
  { id: "c_chumphon", nameEn: "Chumphon Campus", nameTh: "วิทยาเขตชุมพร", type: OrganizationType.Campus },
  { id: "c_trang", nameEn: "Trang Campus", nameTh: "วิทยาเขตตรัง", type: OrganizationType.Campus },
  { id: "c_yala", nameEn: "Yala Campus", nameTh: "วิทยาเขตยะลา", type: OrganizationType.Campus },
];

export const SPORTS_SCHOOLS: Organization[] = [
  { id: "s_chiangmai", nameEn: "Chiang Mai Sports School", nameTh: "โรงเรียนกีฬาจังหวัดเชียงใหม่", type: OrganizationType.SportsSchool },
  { id: "s_nakhonsawan", nameEn: "Nakhon Sawan Sports School", nameTh: "โรงเรียนกีฬาจังหวัดนครสวรรค์", type: OrganizationType.SportsSchool },
  { id: "s_lampang", nameEn: "Lampang Sports School", nameTh: "โรงเรียนกีฬาจังหวัดลำปาง", type: OrganizationType.SportsSchool },
  { id: "s_chonburi", nameEn: "Chonburi Sports School", nameTh: "โรงเรียนกีฬาจังหวัดชลบุรี", type: OrganizationType.SportsSchool },
  { id: "s_nakhonnayok", nameEn: "Nakhon Nayok Sports School", nameTh: "โรงเรียนกีฬาจังหวัดนครนายก", type: OrganizationType.SportsSchool },
  { id: "s_suphanburi", nameEn: "Suphan Buri Sports School", nameTh: "โรงเรียนกีฬาจังหวัดสุพรรณบุรี", type: OrganizationType.SportsSchool },
  { id: "s_angthong", nameEn: "Ang Thong Sports School", nameTh: "โรงเรียนกีฬาจังหวัดอ่างทอง", type: OrganizationType.SportsSchool },
  { id: "s_khonkaen", nameEn: "Khon Kaen Sports School", nameTh: "โรงเรียนกีฬาจังหวัดขอนแก่น", type: OrganizationType.SportsSchool },
  { id: "s_sisaket", nameEn: "Sisaket Sports School", nameTh: "โรงเรียนกีฬาจังหวัดศรีสะเกษ", type: OrganizationType.SportsSchool },
  { id: "s_ubon", nameEn: "Ubon Ratchathani Sports School", nameTh: "โรงเรียนกีฬาจังหวัดอุบลราชธานี", type: OrganizationType.SportsSchool },
  { id: "s_trang", nameEn: "Trang Sports School", nameTh: "โรงเรียนกีฬาจังหวัดตรัง", type: OrganizationType.SportsSchool },
  { id: "s_nakhonsi", nameEn: "Nakhon Si Thammarat Sports School", nameTh: "โรงเรียนกีฬาจังหวัดนครศรีธรรมราช", type: OrganizationType.SportsSchool },
  { id: "s_yala", nameEn: "Yala Sports School", nameTh: "โรงเรียนกีฬาจังหวัดยะลา", type: OrganizationType.SportsSchool },
];

export const FACULTIES: Organization[] = [
  { id: "f_sci", nameEn: "Faculty of Sports Science and Health", nameTh: "คณะวิทยาศาสตร์การกีฬาและสุขภาพ", type: OrganizationType.Campus }, 
  { id: "f_arts", nameEn: "Faculty of Liberal Arts", nameTh: "คณะศิลปศาสตร์", type: OrganizationType.Campus },
  { id: "f_edu", nameEn: "Faculty of Education", nameTh: "คณะศึกษาศาสตร์", type: OrganizationType.Campus },
];

export const ALL_ORGANIZATIONS = [...CENTRAL_OFFICE, ...CAMPUSES, ...SPORTS_SCHOOLS, ...FACULTIES];

// --- APP CONSTANTS ---
export const LOGO_URL = "https://lh3.googleusercontent.com/d/1cRjmEPgytoyDLRYvoegnN3OaqrayaF-c";

// --- TRANSLATIONS ---

export const TRANSLATIONS = {
  en: {
    appTitle: "TNSU Research Data System",
    appSubtitle: "Thailand National Sports University",
    loginTitle: "Login to System",
    loginSubtitle: "Please select your affiliation",
    selectType: "Select Organization Type",
    selectOrg: "Select Organization",
    enterName: "Enter Username",
    enterPass: "Enter Password",
    loginButton: "Login",
    logout: "Logout",
    dashboard: "Dashboard",
    projects: "Projects Master",
    publications: "Publications",
    personnel: "Personnel Dev",
    utilization: "Utilization",
    ip_mou: "IP & MOU",
    users: "User Management",
    totalProjects: "Total Projects",
    totalPubs: "Total Publications",
    successRate: "Avg. Success Rate",
    addProject: "New Project",
    editProject: "Edit Project",
    edit: "Edit",
    delete: "Delete",
    addPub: "Add Publication",
    addUtil: "Add Utilization",
    addPersonnel: "Add Personnel Dev",
    addUser: "Add User",
    editUser: "Edit User",
    editUtil: "Edit Utilization",
    editPersonnel: "Edit Personnel Dev",
    fiscalYear: "Fiscal Year",
    status: "Status",
    project: "Project",
    researcher: "Researcher",
    budget: "Budget",
    cancel: "Cancel",
    save: "Save",
    reportYear: "Output Reporting Year (KPI)",
    linkProject: "Link to Original Project (Source)",
    histMode: "Historical Data Entry Mode",
    welcome: "Welcome",
    role: "Role",
    typeOffice: "Office of the President",
    typeCampus: "Campus",
    typeSchool: "Sports School",
    fundingYear: "Funding Fiscal Year",
    campusOrg: "Campus / Organization",
    projectName: "Project Name",
    fundingSource: "Funding Source",
    category: "Category",
    title: "Article Title",
    type: "Type",
    level: "Level",
    searchPlaceholder: "Search...",
    chatTitle: "TNSU AI Analyst",
    chatSubtitle: "Powered by Gemini 3 Pro",
    chatPlaceholder: "Ask about data trends...",
    projectDetails: "Project Details",
    backToList: "Back to List",
    noPubs: "No publications linked to this project.",
    noUtils: "No utilization records found.",
    utilType: "Utilization Type",
    description: "Description",
    utilDescription: "Description of Impact / Usage",
    staffName: "Staff Name",
    courseName: "Course / Project Name",
    devType: "Development Type",
    activityDate: "Activity Date",
    duration: "Duration (Hours)",
    certificate: "Certificate / Report",
    uploadCert: "Upload File",
    noFile: "No file chosen",
    
    // Module 5
    mou: "Memorandum of Understanding (MOU)",
    ip: "Intellectual Property (IP)",
    addMOU: "Add MOU",
    addIP: "Add IP",
    externalOrg: "External Organization",
    signDate: "Sign Date",
    scope: "Scope of Cooperation",
    workName: "Innovation / Work Name",
    ipType: "IP Type",
    regNo: "Request / Registration No.",
    regDate: "Registration Date",

    // User Management
    username: "Username",
    password: "Password",
    email: "Email",
    confirmDeleteUser: "Are you sure you want to delete this user?",
    loginError: "Invalid credentials or user does not belong to the selected organization.",
    adminRole: "Administrator",
    userRole: "User/Staff",
    importCsv: "Import CSV",
    downloadTemplate: "Download Template",
    importSuccess: "Successfully imported users!",
    importError: "Error importing CSV. Check format.",
    processing: "Processing...",
    systemLogs: "System Logs / Audit Trail",
    userList: "User List",
    logAction: "Action",
    logUser: "User",
    logDetails: "Details",
    logTime: "Timestamp",
  },
  th: {
    appTitle: "ระบบฐานข้อมูลวิจัยและนวัตกรรม TNSU",
    appSubtitle: "มหาวิทยาลัยการกีฬาแห่งชาติ",
    loginTitle: "เข้าสู่ระบบ",
    loginSubtitle: "กรุณาเลือกสังกัดของคุณ",
    selectType: "เลือกประเภทหน่วยงาน",
    selectOrg: "เลือกหน่วยงาน",
    enterName: "กรอกชื่อผู้ใช้งาน",
    enterPass: "กรอกรหัสผ่าน",
    loginButton: "เข้าสู่ระบบ",
    logout: "ออกจากระบบ",
    dashboard: "แดชบอร์ด",
    projects: "ข้อมูลโครงการวิจัย",
    publications: "ผลงานตีพิมพ์",
    personnel: "พัฒนาบุคลากร",
    utilization: "การนำไปใช้ประโยชน์",
    ip_mou: "ทรัพย์สินทางปัญญา & MOU",
    users: "ผู้ใช้งานระบบ",
    totalProjects: "โครงการทั้งหมด",
    totalPubs: "ผลงานตีพิมพ์ทั้งหมด",
    successRate: "อัตราความสำเร็จเฉลี่ย",
    addProject: "เพิ่มโครงการใหม่",
    editProject: "แก้ไขโครงการ",
    edit: "แก้ไข",
    delete: "ลบ",
    addPub: "เพิ่มผลงานตีพิมพ์",
    addUtil: "เพิ่มข้อมูลการนำไปใช้ประโยชน์",
    addPersonnel: "เพิ่มข้อมูลพัฒนาบุคลากร",
    addUser: "เพิ่มผู้ใช้งาน",
    editUser: "แก้ไขผู้ใช้งาน",
    editUtil: "แก้ไขข้อมูลการนำไปใช้ประโยชน์",
    editPersonnel: "แก้ไขข้อมูลพัฒนาบุคลากร",
    fiscalYear: "ปีงบประมาณ",
    status: "สถานะ",
    project: "โครงการ",
    researcher: "นักวิจัย",
    budget: "งบประมาณ",
    cancel: "ยกเลิก",
    save: "บันทึก",
    reportYear: "ปีงบประมาณที่รายงานผล (KPI)",
    linkProject: "เชื่อมโยงกับโครงการต้นทาง (แหล่งทุน)",
    histMode: "โหมดบันทึกข้อมูลย้อนหลัง",
    welcome: "ยินดีต้อนรับ",
    role: "บทบาท",
    typeOffice: "สำนักงานอธิการบดี",
    typeCampus: "วิทยาเขต",
    typeSchool: "โรงเรียนกีฬา",
    fundingYear: "ปีงบประมาณที่ได้รับทุน",
    campusOrg: "วิทยาเขต / หน่วยงาน",
    projectName: "ชื่อโครงการวิจัย",
    fundingSource: "แหล่งทุน",
    category: "หมวดหมู่",
    title: "ชื่อบทความ",
    type: "ประเภท",
    level: "ระดับ",
    searchPlaceholder: "ค้นหา...",
    chatTitle: "ผู้ช่วยวิเคราะห์ AI TNSU",
    chatSubtitle: "ขับเคลื่อนโดย Gemini 3 Pro",
    chatPlaceholder: "สอบถามเกี่ยวกับแนวโน้มข้อมูล...",
    projectDetails: "รายละเอียดโครงการ",
    backToList: "กลับสู่รายการ",
    noPubs: "ไม่พบผลงานตีพิมพ์ที่เกี่ยวข้อง",
    noUtils: "ไม่พบข้อมูลการนำไปใช้ประโยชน์",
    utilType: "ประเภทการนำไปใช้",
    description: "รายละเอียด",
    utilDescription: "รายละเอียดผลกระทบ / การนำไปใช้",
    staffName: "ชื่อ-สกุล บุคลากร",
    courseName: "ชื่อหลักสูตร / โครงการ",
    devType: "รูปแบบการพัฒนา",
    activityDate: "วันที่จัดกิจกรรม",
    duration: "จำนวนชั่วโมง",
    certificate: "แนบรายงาน/เกียรติบัตร",
    uploadCert: "อัปโหลดไฟล์",
    noFile: "ไม่ได้เลือกไฟล์",
    
    // Module 5
    mou: "ความร่วมมือ (MOU)",
    ip: "ทรัพย์สินทางปัญญา (IP)",
    addMOU: "เพิ่ม MOU",
    addIP: "เพิ่มทรัพย์สินทางปัญญา",
    externalOrg: "ชื่อหน่วยงานภายนอก",
    signDate: "วันที่ลงนาม",
    scope: "ขอบเขตความร่วมมือ",
    workName: "ชื่อผลงานนวัตกรรม",
    ipType: "ประเภท",
    regNo: "เลขที่คำขอ / เลขทะเบียน",
    regDate: "วันที่จดทะเบียน",

    // User Management
    username: "ชื่อผู้ใช้",
    password: "รหัสผ่าน",
    email: "อีเมล",
    confirmDeleteUser: "คุณแน่ใจหรือไม่ที่จะลบผู้ใช้นี้?",
    loginError: "ชื่อผู้ใช้/รหัสผ่านไม่ถูกต้อง หรือผู้ใช้ไม่ได้สังกัดหน่วยงานที่เลือก",
    adminRole: "ผู้ดูแลระบบ (Admin)",
    userRole: "เจ้าหน้าที่ (User)",
    importCsv: "นำเข้าจาก CSV",
    downloadTemplate: "โหลดแม่แบบ CSV",
    importSuccess: "นำเข้าผู้ใช้งานสำเร็จ!",
    importError: "เกิดข้อผิดพลาดในการนำเข้า กรุณาตรวจสอบรูปแบบไฟล์",
    processing: "กำลังประมวลผล...",
    systemLogs: "บันทึกการใช้งานระบบ (Audit Log)",
    userList: "รายชื่อผู้ใช้งาน",
    logAction: "การกระทำ",
    logUser: "ผู้ดำเนินการ",
    logDetails: "รายละเอียด",
    logTime: "เวลา",
  }
};
