
import { FiscalYear, FundingSource, ProjectStatus, ResearchCategory, PublicationLevel, PublicationType, OrganizationType, Organization, UtilizationType, DevelopmentType, IPType } from "./types";

export const FISCAL_YEARS = Object.values(FiscalYear);
export const FUNDING_SOURCES = Object.values(FundingSource);
export const PROJECT_STATUSES = Object.values(ProjectStatus);
export const RESEARCH_CATEGORIES = Object.values(ResearchCategory);
export const PUBLICATION_LEVELS = Object.values(PublicationLevel);
export const PUBLICATION_TYPES = Object.values(PublicationType);
export const UTILIZATION_TYPES = Object.values(UtilizationType);
export const DEVELOPMENT_TYPES = Object.values(DevelopmentType);
export const IP_TYPES = Object.values(IPType);

// --- ORGANIZATIONS DATA ---

export const CENTRAL_OFFICE: Organization[] = [
  { id: "c_office", nameEn: "Office of the President", nameTh: "สำนักงานอธิการบดี", type: OrganizationType.OfficePresident }
];

export const CAMPUSES: Organization[] = [
  { id: "c_chiangmai", nameEn: "Chiang Mai Campus", nameTh: "วิทยาเขตเชียงใหม่", type: OrganizationType.Campus },
  { id: "c_phetchabun", nameEn: "Phetchabun Campus", nameTh: "วิทยาเขตเพชรบูรณ์", type: OrganizationType.Campus },
  { id: "c_lampang", nameEn: "Lampang Campus", nameTh: "วิทยาเขตลำปาง", type: OrganizationType.Campus },
  { id: "c_sukhothai", nameEn: "Sukhothai Campus", nameTh: "วิทยาเขตสุโขทัย", type: OrganizationType.Campus },
  { id: "c_bangkok", nameEn: "Bangkok Campus", nameTh: "วิทยาเขตกรุงเทพ", type: OrganizationType.Campus },
  { id: "c_chonburi", nameEn: "Chonburi Campus", nameTh: "วิทยาเขตชลบุรี", type: OrganizationType.Campus },
  { id: "c_samutsakhon", nameEn: "Samut Sakhon Campus", nameTh: "วิทยาเขตสมุทรสาคร", type: OrganizationType.Campus },
  { id: "c_suphanburi", nameEn: "Suphan Buri Campus", nameTh: "วิทยาเขตสุพรรณบุรี", type: OrganizationType.Campus },
  { id: "c_angthong", nameEn: "Ang Thong Campus", nameTh: "วิทยาเขตอ่างทอง", type: OrganizationType.Campus },
  { id: "c_chaiyaphum", nameEn: "Chaiyaphum Campus", nameTh: "วิทยาเขตชัยภูมิ", type: OrganizationType.Campus },
  { id: "c_mahasarakham", nameEn: "Maha Sarakham Campus", nameTh: "วิทยาเขตมหาสารคาม", type: OrganizationType.Campus },
  { id: "c_sisaket", nameEn: "Sisaket Campus", nameTh: "วิทยาเขตศรีสะเกษ", type: OrganizationType.Campus },
  { id: "c_udonthani", nameEn: "Udon Thani Campus", nameTh: "วิทยาเขตอุดรธานี", type: OrganizationType.Campus },
  { id: "c_krabi", nameEn: "Krabi Campus", nameTh: "วิทยาเขตกระบี่", type: OrganizationType.Campus },
  { id: "c_chumphon", nameEn: "Chumphon Campus", nameTh: "วิทยาเขตชุมพร", type: OrganizationType.Campus },
  { id: "c_trang", nameEn: "Trang Campus", nameTh: "วิทยาเขตตรัง", type: OrganizationType.Campus },
  { id: "c_yala", nameEn: "Yala Campus", nameTh: "วิทยาเขตยะลา", type: OrganizationType.Campus },
];

export const SPORTS_SCHOOLS: Organization[] = [
  { id: "s_chiangmai", nameEn: "Chiang Mai Sports School", nameTh: "โรงเรียนกีฬาจังหวัดเชียงใหม่", type: OrganizationType.SportsSchool },
  { id: "s_nakhonsawan", nameEn: "Nakhon Sawan Sports School", nameTh: "โรงเรียนกีฬาจังหวัดนครสวรรค์", type: OrganizationType.SportsSchool },
  { id: "s_lampang", nameEn: "Lampang Sports School", nameTh: "โรงเรียนกีฬาจังหวัดลำปาง", type: OrganizationType.SportsSchool },
  { id: "s_chonburi", nameEn: "Chonburi Sports School", nameTh: "โรงเรียนกีฬาจังหวัดชลบุรี", type: OrganizationType.SportsSchool },
  { id: "s_nakhonnayok", nameEn: "Nakhon Nayok Sports School", nameTh: "โรงเรียนกีฬาจังหวัดนครนายก", type: OrganizationType.SportsSchool },
  { id: "s_suphanburi", nameEn: "Suphan Buri Sports School", nameTh: "โรงเรียนกีฬาจังหวัดสุพรรณบุรี", type: OrganizationType.SportsSchool },
  { id: "s_angthong", nameEn: "Ang Thong Sports School", nameTh: "โรงเรียนกีฬาจังหวัดอ่างทอง", type: OrganizationType.SportsSchool },
  { id: "s_khonkaen", nameEn: "Khon Kaen Sports School", nameTh: "โรงเรียนกีฬาจังหวัดขอนแก่น", type: OrganizationType.SportsSchool },
  { id: "s_sisaket", nameEn: "Sisaket Sports School", nameTh: "โรงเรียนกีฬาจังหวัดศรีสะเกษ", type: OrganizationType.SportsSchool },
  { id: "s_ubon", nameEn: "Ubon Ratchathani Sports School", nameTh: "โรงเรียนกีฬาจังหวัดอุบลราชธานี", type: OrganizationType.SportsSchool },
  { id: "s_trang", nameEn: "Trang Sports School", nameTh: "โรงเรียนกีฬาจังหวัดตรัง", type: OrganizationType.SportsSchool },
  { id: "s_nakhonsi", nameEn: "Nakhon Si Thammarat Sports School", nameTh: "โรงเรียนกีฬาจังหวัดนครศรีธรรมราช", type: OrganizationType.SportsSchool },
  { id: "s_yala", nameEn: "Yala Sports School", nameTh: "โรงเรียนกีฬาจังหวัดยะลา", type: OrganizationType.SportsSchool },
];

export const FACULTIES: Organization[] = [
  { id: "f_sci", nameEn: "Faculty of Sports Science and Health", nameTh: "คณะวิทยาศาสตร์การกีฬาและสุขภาพ", type: OrganizationType.Campus }, 
  { id: "f_arts", nameEn: "Faculty of Liberal Arts", nameTh: "คณะศิลปศาสตร์", type: OrganizationType.Campus },
  { id: "f_edu", nameEn: "Faculty of Education", nameTh: "คณะศึกษาศาสตร์", type: OrganizationType.Campus },
];

export const ALL_ORGANIZATIONS = [...CENTRAL_OFFICE, ...CAMPUSES, ...SPORTS_SCHOOLS, ...FACULTIES];

// --- APP CONSTANTS ---
export const LOGO_URL = "https://lh3.googleusercontent.com/d/1cRjmEPgytoyDLRYvoegnN3OaqrayaF-c";

// --- TRANSLATIONS ---

export const TRANSLATIONS = {
  en: {
    appTitle: "TNSU Research Data System",
    appSubtitle: "Thailand National Sports University",
    loginTitle: "Login to System",
    loginSubtitle: "Please select your affiliation",
    selectType: "Select Organization Type",
    selectOrg: "Select Organization",
    enterName: "Enter Username",
    enterPass: "Enter Password",
    usernameOrEmail: "Username or Email Address",
    loginButton: "Login",
    logout: "Logout",
    dashboard: "Dashboard",
    projects: "Research Projects",
    publications: "Publications",
    personnel: "Personnel Dev",
    utilization: "Utilization",
    ip_mou: "IP & MOU",
    users: "User Management",
    totalProjects: "Total Projects",
    totalPubs: "Total Publications",
    successRate: "Avg. Success Rate",
    addProject: "Register New Project",
    editProject: "Edit Project Details",
    edit: "Edit",
    delete: "Delete",
    addPub: "Add New Publication",
    addUtil: "Add Utilization Record",
    addPersonnel: "Add Personnel Record",
    addUser: "Add New User",
    editUser: "Edit User Profile",
    editUtil: "Edit Utilization Record",
    editPersonnel: "Edit Personnel Record",
    fiscalYear: "Fiscal Year",
    status: "Project Status",
    project: "Project",
    researcher: "Head Researcher",
    budget: "Allocated Budget (THB)",
    cancel: "Cancel",
    save: "Save Data",
    reportYear: "Output Reporting Year (KPI)",
    linkProject: "Source Project (Funding Source)",
    histMode: "Historical Data Entry Mode",
    welcome: "Welcome",
    role: "User Role",
    typeOffice: "Office of the President",
    typeCampus: "Campus",
    typeSchool: "Sports School",
    fundingYear: "Fiscal Year (Funding)",
    campusOrg: "Owner Organization / Campus",
    projectName: "Project Name (Thai/Eng)",
    fundingSource: "Funding Source",
    category: "Research Category",
    title: "Article / Output Title",
    type: "Type",
    level: "Publication Level",
    searchPlaceholder: "Search data...",
    chatTitle: "TNSU AI Analyst",
    chatSubtitle: "Powered by Gemini 3 Pro",
    chatPlaceholder: "Ask about research trends (e.g., 'Summary of 2567')...",
    projectDetails: "Project Details",
    backToList: "Back to List",
    noPubs: "No publications linked to this project yet.",
    noUtils: "No utilization records found.",
    utilType: "Utilization Type",
    description: "Description",
    utilDescription: "Impact Description / Utilization Details",
    staffName: "Staff Name (Researcher)",
    courseName: "Course / Conference Name",
    devType: "Development Type",
    activityDate: "Activity Date",
    duration: "Duration (Hours)",
    certificate: "Certificate / Report",
    uploadCert: "Upload File",
    noFile: "No file chosen",
    fileUrlLabel: "Full Paper URL (Google Drive / PDF)",
    evidenceUrlLabel: "Evidence URL (Photos / Docs)",
    certUrlLabel: "Certificate / Report URL (PDF)",
    
    // Module 5
    mou: "Memorandum of Understanding (MOU)",
    ip: "Intellectual Property (IP)",
    addMOU: "Add MOU Record",
    addIP: "Add IP Record",
    externalOrg: "External Organization Name",
    signDate: "Signing Date",
    scope: "Scope of Cooperation",
    workName: "Innovation / Work Name",
    ipType: "IP Type",
    regNo: "Request / Registration No.",
    regDate: "Registration Date",

    // User Management
    username: "Username",
    password: "Password",
    email: "Email Address",
    confirmDeleteUser: "Are you sure you want to delete this user? This action cannot be undone.",
    loginError: "Invalid credentials or user does not belong to the selected organization.",
    adminRole: "Administrator",
    userRole: "User/Staff",
    importCsv: "Import CSV",
    downloadTemplate: "Download Template",
    importSuccess: "Successfully imported users!",
    importError: "Error importing CSV. Check format.",
    processing: "Processing...",
    systemLogs: "System Logs / Audit Trail",
    userList: "User List",
    logAction: "Action",
    logUser: "Actor",
    logDetails: "Details",
    logTime: "Timestamp",
  },
  th: {
    appTitle: "ระบบสารสนเทศวิจัยและนวัตกรรม TNSU",
    appSubtitle: "มหาวิทยาลัยการกีฬาแห่งชาติ",
    loginTitle: "เข้าสู่ระบบสารสนเทศ",
    loginSubtitle: "กรุณาเลือกสังกัดและระบุตัวตน",
    selectType: "ประเภทหน่วยงานต้นสังกัด",
    selectOrg: "ระบุหน่วยงานของคุณ",
    enterName: "ชื่อผู้ใช้งาน",
    enterPass: "รหัสผ่าน",
    usernameOrEmail: "ชื่อผู้ใช้งาน หรือ อีเมล (Username / Email)",
    loginButton: "เข้าสู่ระบบ (Login)",
    logout: "ออกจากระบบ",
    dashboard: "ภาพรวมระบบ (Dashboard)",
    projects: "ฐานข้อมูลโครงการวิจัย",
    publications: "ผลงานตีพิมพ์และเผยแพร่",
    personnel: "พัฒนาบุคลากรวิจัย",
    utilization: "การนำไปใช้ประโยชน์",
    ip_mou: "ทรัพย์สินทางปัญญา/MOU",
    users: "จัดการผู้ใช้งาน (Admin)",
    totalProjects: "โครงการทั้งหมด",
    totalPubs: "ผลงานตีพิมพ์ทั้งหมด",
    successRate: "อัตราความสำเร็จ (มีผลงาน)",
    addProject: "บันทึกโครงการวิจัยใหม่",
    editProject: "แก้ไขข้อมูลโครงการ",
    edit: "แก้ไข",
    delete: "ลบข้อมูล",
    addPub: "เพิ่มข้อมูลผลงานตีพิมพ์",
    addUtil: "เพิ่มข้อมูลการนำไปใช้ประโยชน์",
    addPersonnel: "เพิ่มประวัติการพัฒนาบุคลากร",
    addUser: "เพิ่มผู้ใช้งานใหม่",
    editUser: "แก้ไขข้อมูลผู้ใช้งาน",
    editUtil: "แก้ไขข้อมูลการนำไปใช้ประโยชน์",
    editPersonnel: "แก้ไขประวัติการพัฒนาบุคลากร",
    fiscalYear: "ปีงบประมาณ",
    status: "สถานะโครงการ",
    project: "โครงการ",
    researcher: "หัวหน้าโครงการวิจัย",
    budget: "งบประมาณที่ได้รับ (บาท)",
    cancel: "ยกเลิก (Cancel)",
    save: "บันทึกข้อมูล (Save)",
    reportYear: "ปีงบประมาณที่ส่งมอบผลงาน (KPI)",
    linkProject: "อ้างอิงโครงการวิจัย (แหล่งทุนต้นทาง)",
    histMode: "โหมดบันทึกข้อมูลย้อนหลัง (Historical Data)",
    welcome: "ยินดีต้อนรับ",
    role: "สิทธิ์การใช้งาน",
    typeOffice: "สำนักงานอธิการบดี",
    typeCampus: "วิทยาเขต",
    typeSchool: "โรงเรียนกีฬา",
    fundingYear: "ปีงบประมาณที่ได้รับจัดสรร",
    campusOrg: "หน่วยงาน / วิทยาเขต เจ้าของโครงการ",
    projectName: "ชื่อโครงการวิจัย (ภาษาไทย/อังกฤษ)",
    fundingSource: "แหล่งทุนสนับสนุน",
    category: "กลุ่มสาขาวิจัย",
    title: "ชื่อบทความวิจัย / ชื่อผลงาน",
    type: "ประเภทฐานข้อมูล",
    level: "ระดับการเผยแพร่",
    searchPlaceholder: "ค้นหาข้อมูล...",
    chatTitle: "ผู้ช่วยวิเคราะห์ AI TNSU",
    chatSubtitle: "ขับเคลื่อนโดย Gemini 3 Pro",
    chatPlaceholder: "สอบถามข้อมูลวิจัย (เช่น สรุปยอดปี 2568)...",
    projectDetails: "รายละเอียดโครงการวิจัย",
    backToList: "กลับสู่หน้ารายการ",
    noPubs: "ยังไม่มีผลงานตีพิมพ์ที่เชื่อมโยงกับโครงการนี้",
    noUtils: "ยังไม่มีข้อมูลการนำไปใช้ประโยชน์",
    utilType: "รูปแบบการนำไปใช้ประโยชน์",
    description: "รายละเอียด",
    utilDescription: "รายละเอียดผลกระทบ / การนำไปใช้จริง",
    staffName: "ชื่อ-สกุล บุคลากร",
    courseName: "ชื่อหลักสูตรอบรม / หัวข้อการประชุม",
    devType: "รูปแบบกิจกรรม",
    activityDate: "วันที่เข้าร่วมกิจกรรม",
    duration: "จำนวนชั่วโมง (ชม.)",
    certificate: "เอกสารแนบ / เกียรติบัตร",
    uploadCert: "อัปโหลดไฟล์",
    noFile: "ยังไม่ได้เลือกไฟล์",
    fileUrlLabel: "ลิงก์ไฟล์เอกสารฉบับเต็ม (Google Drive / PDF)",
    evidenceUrlLabel: "ลิงก์หลักฐานการนำไปใช้ (รูปภาพ / เอกสาร)",
    certUrlLabel: "ลิงก์เกียรติบัตร / รายงานผล (PDF)",
    
    // Module 5
    mou: "บันทึกความร่วมมือ (MOU)",
    ip: "ทรัพย์สินทางปัญญา (IP)",
    addMOU: "เพิ่มข้อมูล MOU",
    addIP: "เพิ่มข้อมูลทรัพย์สินทางปัญญา",
    externalOrg: "ชื่อหน่วยงานภายนอก (คู่ความร่วมมือ)",
    signDate: "วันที่ลงนาม",
    scope: "ขอบเขตความร่วมมือ",
    workName: "ชื่อผลงานนวัตกรรม / สิ่งประดิษฐ์",
    ipType: "ประเภททรัพย์สินทางปัญญา",
    regNo: "เลขที่คำขอ / เลขทะเบียน",
    regDate: "วันที่จดทะเบียน / ยื่นคำขอ",

    // User Management
    username: "ชื่อผู้ใช้งาน (Username)",
    password: "รหัสผ่าน",
    email: "อีเมล (Email)",
    confirmDeleteUser: "ยืนยันการลบผู้ใช้งานรายนี้? (ไม่สามารถกู้คืนได้)",
    loginError: "ชื่อผู้ใช้/รหัสผ่านไม่ถูกต้อง หรือผู้ใช้ไม่ได้สังกัดหน่วยงานที่เลือก",
    adminRole: "ผู้ดูแลระบบ (Admin)",
    userRole: "เจ้าหน้าที่ (User)",
    importCsv: "นำเข้าไฟล์ CSV",
    downloadTemplate: "ดาวน์โหลดแบบฟอร์ม CSV",
    importSuccess: "นำเข้าข้อมูลผู้ใช้งานสำเร็จ!",
    importError: "เกิดข้อผิดพลาดในการนำเข้า กรุณาตรวจสอบรูปแบบไฟล์ CSV",
    processing: "กำลังประมวลผล...",
    systemLogs: "บันทึกการใช้งานระบบ (Audit Log)",
    userList: "รายชื่อผู้ใช้งาน",
    logAction: "การกระทำ",
    logUser: "ผู้ดำเนินการ",
    logDetails: "รายละเอียด",
    logTime: "วัน-เวลา",
  }
};
