
import { FiscalYear, FundingSource, ProjectStatus, ResearchCategory, PublicationLevel, PublicationType, OrganizationType, Organization, UtilizationType, DevelopmentType, IPType } from "./types";

export const FISCAL_YEARS = Object.values(FiscalYear);
export const FUNDING_SOURCES = Object.values(FundingSource);
export const PROJECT_STATUSES = Object.values(ProjectStatus);
export const RESEARCH_CATEGORIES = Object.values(ResearchCategory);
export const PUBLICATION_LEVELS = Object.values(PublicationLevel);
export const PUBLICATION_TYPES = Object.values(PublicationType);
export const UTILIZATION_TYPES = Object.values(UtilizationType);
export const DEVELOPMENT_TYPES = Object.values(DevelopmentType);
export const IP_TYPES = Object.values(IPType);

// --- ORGANIZATIONS DATA ---

export const CENTRAL_OFFICE: Organization[] = [
  { id: "c_office", nameEn: "Office of the President", nameTh: "สำนักงานอธิการบดี", type: OrganizationType.OfficePresident }
];

export const CAMPUSES: Organization[] = [
  { id: "c_chiangmai", nameEn: "Chiang Mai Campus", nameTh: "วิทยาเขตเชียงใหม่", type: OrganizationType.Campus },
  { id: "c_phetchabun", nameEn: "Phetchabun Campus", nameTh: "วิทยาเขตเพชรบูรณ์", type: OrganizationType.Campus },
  { id: "c_lampang", nameEn: "Lampang Campus", nameTh: "วิทยาเขตลำปาง", type: OrganizationType.Campus },
  { id: "c_sukhothai", nameEn: "Sukhothai Campus", nameTh: "วิทยาเขตสุโขทัย", type: OrganizationType.Campus },
  { id: "c_bangkok", nameEn: "Bangkok Campus", nameTh: "วิทยาเขตกรุงเทพ", type: OrganizationType.Campus },
  { id: "c_chonburi", nameEn: "Chonburi Campus", nameTh: "วิทยาเขตชลบุรี", type: OrganizationType.Campus },
  { id: "c_samutsakhon", nameEn: "Samut Sakhon Campus", nameTh: "วิทยาเขตสมุทรสาคร", type: OrganizationType.Campus },
  { id: "c_suphanburi", nameEn: "Suphan Buri Campus", nameTh: "วิทยาเขตสุพรรณบุรี", type: OrganizationType.Campus },
  { id: "c_angthong", nameEn: "Ang Thong Campus", nameTh: "วิทยาเขตอ่างทอง", type: OrganizationType.Campus },
  { id: "c_chaiyaphum", nameEn: "Chaiyaphum Campus", nameTh: "วิทยาเขตชัยภูมิ", type: OrganizationType.Campus },
  { id: "c_mahasarakham", nameEn: "Maha Sarakham Campus", nameTh: "วิทยาเขตมหาสารคาม", type: OrganizationType.Campus },
  { id: "c_sisaket", nameEn: "Sisaket Campus", nameTh: "วิทยาเขตศรีสะเกษ", type: OrganizationType.Campus },
  { id: "c_udonthani", nameEn: "Udon Thani Campus", nameTh: "วิทยาเขตอุดรธานี", type: OrganizationType.Campus },
  { id: "c_krabi", nameEn: "Krabi Campus", nameTh: "วิทยาเขตกระบี่", type: OrganizationType.Campus },
  { id: "c_chumphon", nameEn: "Chumphon Campus", nameTh: "วิทยาเขตชุมพร", type: OrganizationType.Campus },
  { id: "c_trang", nameEn: "Trang Campus", nameTh: "วิทยาเขตตรัง", type: OrganizationType.Campus },
  { id: "c_yala", nameEn: "Yala Campus", nameTh: "วิทยาเขตยะลา", type: OrganizationType.Campus },
];

export const SPORTS_SCHOOLS: Organization[] = [
  { id: "s_chiangmai", nameEn: "Chiang Mai Sports School", nameTh: "โรงเรียนกีฬาจังหวัดเชียงใหม่", type: OrganizationType.SportsSchool },
  { id: "s_nakhonsawan", nameEn: "Nakhon Sawan Sports School", nameTh: "โรงเรียนกีฬาจังหวัดนครสวรรค์", type: OrganizationType.SportsSchool },
  { id: "s_lampang", nameEn: "Lampang Sports School", nameTh: "โรงเรียนกีฬาจังหวัดลำปาง", type: OrganizationType.SportsSchool },
  { id: "s_chonburi", nameEn: "Chonburi Sports School", nameTh: "โรงเรียนกีฬาจังหวัดชลบุรี", type: OrganizationType.SportsSchool },
  { id: "s_nakhonnayok", nameEn: "Nakhon Nayok Sports School", nameTh: "โรงเรียนกีฬาจังหวัดนครนายก", type: OrganizationType.SportsSchool },
  { id: "s_suphanburi", nameEn: "Suphan Buri Sports School", nameTh: "โรงเรียนกีฬาจังหวัดสุพรรณบุรี", type: OrganizationType.SportsSchool },
  { id: "s_angthong", nameEn: "Ang Thong Sports School", nameTh: "โรงเรียนกีฬาจังหวัดอ่างทอง", type: OrganizationType.SportsSchool },
  { id: "s_khonkaen", nameEn: "Khon Kaen Sports School", nameTh: "โรงเรียนกีฬาจังหวัดขอนแก่น", type: OrganizationType.SportsSchool },
  { id: "s_sisaket", nameEn: "Sisaket Sports School", nameTh: "โรงเรียนกีฬาจังหวัดศรีสะเกษ", type: OrganizationType.SportsSchool },
  { id: "s_ubon", nameEn: "Ubon Ratchathani Sports School", nameTh: "โรงเรียนกีฬาจังหวัดอุบลราชธานี", type: OrganizationType.SportsSchool },
  { id: "s_trang", nameEn: "Trang Sports School", nameTh: "โรงเรียนกีฬาจังหวัดตรัง", type: OrganizationType.SportsSchool },
  { id: "s_nakhonsi", nameEn: "Nakhon Si Thammarat Sports School", nameTh: "โรงเรียนกีฬาจังหวัดนครศรีธรรมราช", type: OrganizationType.SportsSchool },
  { id: "s_yala", nameEn: "Yala Sports School", nameTh: "โรงเรียนกีฬาจังหวัดยะลา", type: OrganizationType.SportsSchool },
];

export const FACULTIES: Organization[] = [
  { id: "f_sci", nameEn: "Faculty of Sports Science and Health", nameTh: "คณะวิทยาศาสตร์การกีฬาและสุขภาพ", type: OrganizationType.Campus }, 
  { id: "f_arts", nameEn: "Faculty of Liberal Arts", nameTh: "คณะศิลปศาสตร์", type: OrganizationType.Campus },
  { id: "f_edu", nameEn: "Faculty of Education", nameTh: "คณะศึกษาศาสตร์", type: OrganizationType.Campus },
];

export const ALL_ORGANIZATIONS = [...CENTRAL_OFFICE, ...CAMPUSES, ...SPORTS_SCHOOLS, ...FACULTIES];

// --- APP CONSTANTS ---
export const LOGO_URL = "https://lh3.googleusercontent.com/d/1cRjmEPgytoyDLRYvoegnN3OaqrayaF-c";

// --- TRANSLATIONS ---

export const TRANSLATIONS = {
  en: {
    appTitle: "TNSU Research Data System",
    appSubtitle: "Thailand National Sports University",
    loginTitle: "Login to System",
    loginSubtitle: "Please select your affiliation",
    selectType: "Select Organization Type",
    selectOrg: "Select Organization",
    enterName: "Enter Username",
    enterPass: "Enter Password",
    usernameOrEmail: "Username or Email Address",
    loginButton: "Login",
    logout: "Logout",
    dashboard: "Dashboard",
    projects: "Research Projects",
    publications: "Publications",
    personnel: "Personnel Dev",
    utilization: "Utilization",
    ip_mou: "IP & MOU",
    users: "User Management",
    totalProjects: "Total Projects",
    totalPubs: "Total Publications",
    successRate: "Avg. Success Rate",
    addProject: "Register New Project",
    editProject: "Edit Project Details",
    edit: "Edit",
    delete: "Delete",
    addPub: "Add New Publication",
    addUtil: "Add Utilization Record",
    addPersonnel: "Add Personnel Record",
    addUser: "Add New User",
    editUser: "Edit User Profile",
    editUtil: "Edit Utilization Record",
    editPersonnel: "Edit Personnel Record",
    fiscalYear: "Fiscal Year",
    status: "Project Status",
    project: "Project",
    researcher: "Head Researcher",
    budget: "Allocated Budget (THB)",
    cancel: "Cancel",
    save: "Save Data",
    reportYear: "Output Reporting Year (KPI)",
    linkProject: "Source Project (Funding Source)",
    histMode: "Historical Data Entry Mode",
    welcome: "Welcome",
    role: "User Role",
    typeOffice: "Office of the President",
    typeCampus: "Campus",
    typeSchool: "Sports School",
    fundingYear: "Fiscal Year (Funding)",
    campusOrg: "Owner Organization / Campus",
    projectName: "Project Name (Thai/Eng)",
    projectNameTh: "Project Name (Thai)",
    projectNameEn: "Project Name (English)",
    fundingSource: "Funding Source",
    category: "Faculty",
    title: "Article / Output Title",
    type: "Type",
    level: "Publication Level",
    
    // Enum Translations
    "Internal": "Internal Budget",
    "Non-Budget": "Non-Budget",
    "External": "External Funding",
    "Faculty of Sports Science and Health": "Faculty of Sports Science and Health",
    "Faculty of Liberal Arts": "Faculty of Liberal Arts",
    "Faculty of Education": "Faculty of Education",

    searchPlaceholder: "Search data...",
    chatTitle: "TNSU AI Analyst",
    chatSubtitle: "Powered by Gemini 3 Pro",
    chatPlaceholder: "Ask about research trends (e.g., 'Summary of 2567')...",
    projectDetails: "Project Details",
    backToList: "Back to List",
    noPubs: "No publications linked to this project yet.",
    noUtils: "No utilization records found.",
    utilType: "Utilization Type",
    description: "Description",
    utilDescription: "Impact Description / Utilization Details",
    staffName: "Staff Name (Researcher)",
    courseName: "Course / Conference Name",
    devType: "Development Type",
    activityDate: "Activity Date",
    duration: "Duration (Hours)",
    certificate: "Certificate / Report",
    uploadCert: "Upload File",
    noFile: "No file chosen",
    fileUrlLabel: "Full Paper URL (Google Drive / PDF)",
    evidenceUrlLabel: "Evidence URL (Photos / Docs)",
    certUrlLabel: "Certificate / Report URL (PDF)",
    printReport: "Print Report",
    allTypes: "All Organization Types",
    allOrgs: "All Organizations",
    confirmDeleteProject: "Are you sure you want to delete this project? This action cannot be undone.",
    deleteError: "Failed to delete project. Please try again.",
    
    // Module 5
    mou: "Memorandum of Understanding (MOU)",
    ip: "Intellectual Property (IP)",
    addMOU: "Add MOU Record",
    addIP: "Add IP Record",
    externalOrg: "External Organization Name",
    signDate: "Signing Date",
    scope: "Scope of Cooperation",
    workName: "Innovation / Work Name",
    ipType: "IP Type",
    regNo: "Request / Registration No.",
    regDate: "Registration Date",

    // User Management
    username: "Username",
    password: "Password",
    email: "Email Address",
    confirmDeleteUser: "Are you sure you want to delete this user? This action cannot be undone.",
    loginError: "Invalid credentials or user does not belong to the selected organization.",
    adminRole: "Administrator",
    userRole: "User/Staff",
    importCsv: "Import CSV",
    exportCsv: "Export CSV",
    downloadTemplate: "Download Template",
    importSuccess: "Successfully imported users!",
    importError: "Error importing CSV. Check format.",
    processing: "Processing...",
    systemLogs: "System Logs / Audit Trail",
    userList: "User List",
    logAction: "Action",
    logUser: "Actor",
    logDetails: "Details",
    logTime: "Timestamp",
    needAccess: "Need Access?",
    needAccessDesc: "If you cannot log in or need to register, please contact the",
    mainAdmin: "Main Administrator",
    restrictedAccess: "System registration is restricted to authorized personnel only.",
    userManual: "User Manual",
    feedback: "Feedback & Survey",
    submitFeedback: "Submit Feedback",
    rating: "Satisfaction Rating",
    comment: "Comments / Suggestions",
    thankYouFeedback: "Thank you for your feedback!",
    manualDashboard: "Overview of research statistics and key performance indicators.",
    manualProjects: "Manage research projects, funding sources, and budget allocation.",
    manualPublications: "Record and track research publications and academic outputs.",
    manualPersonnel: "Track personnel development activities and training records.",
    manualUtilization: "Record how research outputs are utilized for impact.",
    manualIPMOU: "Manage Intellectual Property (IP) and Memorandums of Understanding (MOU).",
    manualUsers: "Manage system users, roles, and permissions.",
    tips: "Tips:",
    tipCSV: "Use the 'Import CSV' button to bulk upload data.",
    tipEdit: "Click 'Edit' on any row to modify existing records.",
    tipSearch: "Use the search bar to filter large datasets.",
    tipCSVCodes: "Check 'Data Format Guide' in Import CSV window for valid codes (campus_id, status, etc).",
    close: "Close",
    selectSection: "Select a section to view details.",
    feedbackSuccessDesc: "Your input helps us improve.",
    feedbackPlaceholder: "Tell us what you think...",
    allYears: "All Years",
    
    // CSV Import Modal
    importDataTitle: "Import Data",
    step1: "Step 1: Download Template",
    step1Desc: "Use our template to ensure your data is formatted correctly.",
    downloadTemplateBtn: "Download CSV Template",
    step2: "Step 2: Upload CSV",
    selectFileError: "Please select a file.",
    emptyFileError: "The file appears to be empty.",
    importErrorMsg: "Failed to parse or import CSV. Please check the file format.",
    dataFormatGuide: "Data Format Guide (Click to expand)",
    validFiscalYears: "Fiscal Years (fiscal_year):",
    validCampusIds: "Valid Campus IDs (campus_id):",
    validStatus: "Project Status (status):",
    validPubLevel: "Publication Level (publication_level):",
    validPubType: "Publication Type (publication_type):",
    validIpType: "IP Type (ip_type):",
    validRefProjectId: "Reference Project ID (ref_project_id):",
    validRefProjectIdDesc: "Must match an existing Project ID in the system. Check the 'Research Projects' tab for valid IDs.",
    validRoles: "User Roles (role):",
    roleAdminDesc: "Full system access",
    roleUserDesc: "Restricted access (can only view/edit own data)",
    defaultPasswordLabel: "Default Password:",
    defaultPasswordDesc: "All imported users will be assigned the password:",
    importBtn: "Import Data",

    // Change Password Modal
    changePasswordTitle: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    minCharError: "New password must be at least 6 characters.",
    passwordMatchError: "New passwords do not match.",
    passwordChangeFail: "Failed to change password.",
    unexpectedError: "An unexpected error occurred.",
    passwordChangedSuccess: "Password Changed!",
    passwordChangedDesc: "Your password has been updated successfully.",
    updatePasswordBtn: "Update Password",
    minCharHint: "Minimum 6 characters",

    // User Management & Form
    confirmResetPassword: "Send password reset email to {email}?",
    resetPasswordSuccess: "Password reset email sent successfully.",
    resetPasswordError: "Error: ",
    noUsersFound: "No users found matching filters.",
    refresh: "Refresh",
    noLogsFound: "No logs found.",
    loading: "Loading...",
    loadMoreLogs: "Load More Logs",
    passwordPlaceholderEdit: "******** (Leave empty to keep)",
    passwordPlaceholderNew: "Set password",
    passwordResetHint: "Enter new password only if you want to reset it.",

    // Publication Form
    linkProjectSourceAlert: "Please link a project source.",
    linkProjectDesc: "Link an output to its original funding source (Cross-Year Mapping)",
    currentYearNote: "Please ensure the reporting year is set to the current fiscal year.",
    noProjectsFound: "No projects found matching your search.",
    fundedLabel: "Funded: ",
    pasteLinkHint: "Paste a link to your document (e.g., Google Drive, Dropbox, or Website).",

    // Personnel Form
    fillRequiredFields: "Please fill in all required fields.",
    staffNamePlaceholder: "e.g. Dr. Somchai Jai-dee",
    courseNamePlaceholder: "e.g. Advanced Sports Analytics Workshop",
    urlPlaceholder: "https://drive.google.com/...",

    // Utilization Form
    enterDescriptionAlert: "Please enter a description.",
    utilizationDesc: "Record how research outputs are being utilized or creating impact.",
    utilDescriptionPlaceholder: "Describe how the research outcome was utilized...",
  },
  th: {
    appTitle: "ระบบสารสนเทศวิจัยและนวัตกรรม TNSU",
    appSubtitle: "มหาวิทยาลัยการกีฬาแห่งชาติ",
    loginTitle: "เข้าสู่ระบบสารสนเทศ",
    loginSubtitle: "กรุณาเลือกสังกัดและระบุตัวตน",
    selectType: "ประเภทหน่วยงานต้นสังกัด",
    selectOrg: "ระบุหน่วยงานของคุณ",
    enterName: "ชื่อผู้ใช้งาน",
    enterPass: "รหัสผ่าน",
    usernameOrEmail: "ชื่อผู้ใช้งาน หรือ อีเมล (Username / Email)",
    loginButton: "เข้าสู่ระบบ (Login)",
    logout: "ออกจากระบบ",
    dashboard: "ภาพรวมระบบ (Dashboard)",
    projects: "ฐานข้อมูลโครงการวิจัย",
    publications: "ผลงานตีพิมพ์และเผยแพร่",
    personnel: "พัฒนาบุคลากรวิจัย",
    utilization: "การนำไปใช้ประโยชน์",
    ip_mou: "ทรัพย์สินทางปัญญา/MOU",
    users: "จัดการผู้ใช้งาน (Admin)",
    totalProjects: "โครงการทั้งหมด",
    totalPubs: "ผลงานตีพิมพ์ทั้งหมด",
    successRate: "อัตราความสำเร็จ (มีผลงาน)",
    addProject: "บันทึกโครงการวิจัยใหม่",
    editProject: "แก้ไขข้อมูลโครงการ",
    edit: "แก้ไข",
    delete: "ลบข้อมูล",
    addPub: "เพิ่มข้อมูลผลงานตีพิมพ์",
    addUtil: "เพิ่มข้อมูลการนำไปใช้ประโยชน์",
    addPersonnel: "เพิ่มประวัติการพัฒนาบุคลากร",
    addUser: "เพิ่มผู้ใช้งานใหม่",
    editUser: "แก้ไขข้อมูลผู้ใช้งาน",
    editUtil: "แก้ไขข้อมูลการนำไปใช้ประโยชน์",
    editPersonnel: "แก้ไขประวัติการพัฒนาบุคลากร",
    fiscalYear: "ปีงบประมาณ",
    status: "สถานะโครงการ",
    project: "โครงการ",
    researcher: "หัวหน้าโครงการวิจัย",
    budget: "งบประมาณที่ได้รับ (บาท)",
    cancel: "ยกเลิก (Cancel)",
    save: "บันทึกข้อมูล (Save)",
    reportYear: "ปีงบประมาณที่ส่งมอบผลงาน (KPI)",
    linkProject: "อ้างอิงโครงการวิจัย (แหล่งทุนต้นทาง)",
    histMode: "โหมดบันทึกข้อมูลย้อนหลัง (Historical Data)",
    welcome: "ยินดีต้อนรับ",
    role: "สิทธิ์การใช้งาน",
    typeOffice: "สำนักงานอธิการบดี",
    typeCampus: "วิทยาเขต",
    typeSchool: "โรงเรียนกีฬา",
    fundingYear: "ปีงบประมาณที่ได้รับจัดสรร",
    campusOrg: "หน่วยงาน / วิทยาเขต เจ้าของโครงการ",
    projectName: "ชื่อโครงการวิจัย",
    projectNameTh: "ชื่อโครงการวิจัย (ภาษาไทย)",
    projectNameEn: "ชื่อโครงการวิจัย (ภาษาอังกฤษ)",
    fundingSource: "แหล่งทุนสนับสนุน",
    category: "คณะวิชา",
    title: "ชื่อบทความวิจัย / ชื่อผลงาน",
    type: "ประเภทฐานข้อมูล",
    level: "ระดับการเผยแพร่",
    
    // Enum Translations
    "Internal": "งบประมาณรายได้",
    "Non-Budget": "เงินนอกงบประมาณ",
    "External": "แหล่งทุนภายนอก",
    "Faculty of Sports Science and Health": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
    "Faculty of Liberal Arts": "คณะศิลปศาสตร์",
    "Faculty of Education": "คณะศึกษาศาสตร์",

    searchPlaceholder: "ค้นหาข้อมูล...",
    chatTitle: "ผู้ช่วยวิเคราะห์ AI TNSU",
    chatSubtitle: "ขับเคลื่อนโดย Gemini 3 Pro",
    chatPlaceholder: "สอบถามข้อมูลวิจัย (เช่น สรุปยอดปี 2568)...",
    projectDetails: "รายละเอียดโครงการวิจัย",
    backToList: "กลับสู่หน้ารายการ",
    noPubs: "ยังไม่มีผลงานตีพิมพ์ที่เชื่อมโยงกับโครงการนี้",
    noUtils: "ยังไม่มีข้อมูลการนำไปใช้ประโยชน์",
    utilType: "รูปแบบการนำไปใช้ประโยชน์",
    description: "รายละเอียด",
    utilDescription: "รายละเอียดผลกระทบ / การนำไปใช้จริง",
    staffName: "ชื่อ-สกุล บุคลากร",
    courseName: "ชื่อหลักสูตรอบรม / หัวข้อการประชุม",
    devType: "รูปแบบกิจกรรม",
    activityDate: "วันที่เข้าร่วมกิจกรรม",
    duration: "จำนวนชั่วโมง (ชม.)",
    certificate: "เอกสารแนบ / เกียรติบัตร",
    uploadCert: "อัปโหลดไฟล์",
    noFile: "ยังไม่ได้เลือกไฟล์",
    fileUrlLabel: "ลิงก์ไฟล์เอกสารฉบับเต็ม (Google Drive / PDF)",
    evidenceUrlLabel: "ลิงก์หลักฐานการนำไปใช้ (รูปภาพ / เอกสาร)",
    certUrlLabel: "ลิงก์เกียรติบัตร / รายงานผล (PDF)",
    printReport: "พิมพ์รายงานสรุป",
    allTypes: "ทุกประเภทหน่วยงาน",
    allOrgs: "ทุกหน่วยงาน",
    confirmDeleteProject: "ยืนยันการลบโครงการนี้? (ไม่สามารถกู้คืนได้)",
    deleteError: "ลบโครงการไม่สำเร็จ กรุณาลองใหม่อีกครั้ง",

    // Module 5
    mou: "บันทึกความร่วมมือ (MOU)",
    ip: "ทรัพย์สินทางปัญญา (IP)",
    addMOU: "เพิ่มข้อมูล MOU",
    addIP: "เพิ่มข้อมูลทรัพย์สินทางปัญญา",
    externalOrg: "ชื่อหน่วยงานภายนอก (คู่ความร่วมมือ)",
    signDate: "วันที่ลงนาม",
    scope: "ขอบเขตความร่วมมือ",
    workName: "ชื่อผลงานนวัตกรรม / สิ่งประดิษฐ์",
    ipType: "ประเภททรัพย์สินทางปัญญา",
    regNo: "เลขที่คำขอ / เลขทะเบียน",
    regDate: "วันที่จดทะเบียน / ยื่นคำขอ",

    // User Management
    username: "ชื่อผู้ใช้งาน (Username)",
    password: "รหัสผ่าน",
    email: "อีเมล (Email)",
    confirmDeleteUser: "ยืนยันการลบผู้ใช้งานรายนี้? (ไม่สามารถกู้คืนได้)",
    loginError: "ชื่อผู้ใช้/รหัสผ่านไม่ถูกต้อง หรือผู้ใช้ไม่ได้สังกัดหน่วยงานที่เลือก",
    adminRole: "ผู้ดูแลระบบ (Admin)",
    userRole: "เจ้าหน้าที่ (User)",
    importCsv: "นำเข้าไฟล์ CSV",
    exportCsv: "ส่งออกไฟล์ CSV",
    downloadTemplate: "ดาวน์โหลดแบบฟอร์ม CSV",
    importSuccess: "นำเข้าข้อมูลผู้ใช้งานสำเร็จ!",
    importError: "เกิดข้อผิดพลาดในการนำเข้า กรุณาตรวจสอบรูปแบบไฟล์ CSV",
    processing: "กำลังประมวลผล...",
    systemLogs: "บันทึกการใช้งานระบบ (Audit Log)",
    userList: "รายชื่อผู้ใช้งาน",
    logAction: "การกระทำ",
    logUser: "ผู้ดำเนินการ",
    logDetails: "รายละเอียด",
    logTime: "วัน-เวลา",
    needAccess: "ต้องการเข้าใช้งานระบบ?",
    needAccessDesc: "หากท่านไม่สามารถเข้าสู่ระบบได้ หรือต้องการลงทะเบียนใหม่ กรุณาติดต่อ",
    mainAdmin: "ผู้ดูแลระบบหลัก (Main Administrator)",
    restrictedAccess: "การลงทะเบียนสงวนสิทธิ์เฉพาะเจ้าหน้าที่ที่ได้รับอนุญาตเท่านั้น",
    userManual: "คู่มือการใช้งาน",
    feedback: "ประเมินความพึงพอใจ",
    submitFeedback: "ส่งแบบประเมิน",
    rating: "ระดับความพึงพอใจ",
    comment: "ข้อเสนอแนะเพิ่มเติม",
    thankYouFeedback: "ขอบคุณสำหรับข้อเสนอแนะ!",
    manualDashboard: "แสดงภาพรวมสถิติงานวิจัยและตัวชี้วัดความสำเร็จ (KPI) ของหน่วยงาน",
    manualProjects: "บริหารจัดการข้อมูลโครงการวิจัย แหล่งทุน และงบประมาณ",
    manualPublications: "บันทึกและติดตามผลงานตีพิมพ์ บทความวิจัย และการเผยแพร่ผลงาน",
    manualPersonnel: "ติดตามประวัติการพัฒนาบุคลากร การอบรม และการประชุมวิชาการ",
    manualUtilization: "บันทึกการนำผลงานวิจัยไปใช้ประโยชน์ในด้านต่างๆ",
    manualIPMOU: "จัดการข้อมูลทรัพย์สินทางปัญญา (IP) และบันทึกความร่วมมือ (MOU)",
    manualUsers: "บริหารจัดการผู้ใช้งาน กำหนดสิทธิ์ และตรวจสอบการเข้าใช้งาน",
    tips: "คำแนะนำเพิ่มเติม:",
    tipCSV: "ใช้ปุ่ม 'นำเข้าไฟล์ CSV' เพื่ออัปโหลดข้อมูลจำนวนมาก",
    tipEdit: "คลิกปุ่ม 'แก้ไข' ในแต่ละแถวเพื่อปรับปรุงข้อมูลเดิม",
    tipSearch: "ใช้ช่องค้นหาเพื่อกรองข้อมูลที่ต้องการ",
    tipCSVCodes: "ตรวจสอบรหัส (campus_id, status) ได้ที่ 'คู่มือรูปแบบข้อมูล' ในหน้าต่างนำเข้า CSV",
    close: "ปิด",
    selectSection: "เลือกเมนูเพื่อดูรายละเอียด",
    feedbackSuccessDesc: "ข้อมูลของท่านจะช่วยให้เราปรับปรุงระบบให้ดียิ่งขึ้น",
    feedbackPlaceholder: "บอกเล่าความคิดเห็นของท่าน...",
    allYears: "ทุกปีงบประมาณ",

    // CSV Import Modal
    importDataTitle: "นำเข้าข้อมูล",
    step1: "ขั้นตอนที่ 1: ดาวน์โหลดแบบฟอร์ม",
    step1Desc: "ใช้แบบฟอร์มของเราเพื่อให้แน่ใจว่าข้อมูลถูกต้อง",
    downloadTemplateBtn: "ดาวน์โหลดแบบฟอร์ม CSV",
    step2: "ขั้นตอนที่ 2: อัปโหลดไฟล์ CSV",
    selectFileError: "กรุณาเลือกไฟล์",
    emptyFileError: "ไฟล์ว่างเปล่า",
    importErrorMsg: "เกิดข้อผิดพลาดในการนำเข้า กรุณาตรวจสอบรูปแบบไฟล์",
    dataFormatGuide: "คู่มือรูปแบบข้อมูล (คลิกเพื่อขยาย)",
    validFiscalYears: "ปีงบประมาณ (fiscal_year):",
    validCampusIds: "รหัสหน่วยงาน (campus_id):",
    validStatus: "สถานะโครงการ (status):",
    validPubLevel: "ระดับการเผยแพร่ (publication_level):",
    validPubType: "ประเภทผลงาน (publication_type):",
    validIpType: "ประเภททรัพย์สินทางปัญญา (ip_type):",
    validRefProjectId: "รหัสโครงการอ้างอิง (ref_project_id):",
    validRefProjectIdDesc: "ต้องตรงกับรหัสโครงการที่มีอยู่ในระบบ ตรวจสอบได้ที่เมนู 'ฐานข้อมูลโครงการวิจัย'",
    validRoles: "สิทธิ์ผู้ใช้งาน (role):",
    roleAdminDesc: "เข้าถึงได้ทุกส่วนของระบบ",
    roleUserDesc: "เข้าถึงได้เฉพาะข้อมูลของตนเอง",
    defaultPasswordLabel: "รหัสผ่านเริ่มต้น:",
    defaultPasswordDesc: "ผู้ใช้งานที่นำเข้าทั้งหมดจะใช้รหัสผ่าน:",
    importBtn: "นำเข้าข้อมูล",

    // Change Password Modal
    changePasswordTitle: "เปลี่ยนรหัสผ่าน",
    currentPassword: "รหัสผ่านปัจจุบัน",
    newPassword: "รหัสผ่านใหม่",
    confirmNewPassword: "ยืนยันรหัสผ่านใหม่",
    minCharError: "รหัสผ่านต้องมีความยาวอย่างน้อย 6 ตัวอักษร",
    passwordMatchError: "รหัสผ่านใหม่ไม่ตรงกัน",
    passwordChangeFail: "เปลี่ยนรหัสผ่านไม่สำเร็จ",
    unexpectedError: "เกิดข้อผิดพลาดที่ไม่คาดคิด",
    passwordChangedSuccess: "เปลี่ยนรหัสผ่านสำเร็จ!",
    passwordChangedDesc: "รหัสผ่านของท่านได้รับการปรับปรุงเรียบร้อยแล้ว",
    updatePasswordBtn: "อัปเดตรหัสผ่าน",
    minCharHint: "ขั้นต่ำ 6 ตัวอักษร",

    // User Management & Form
    confirmResetPassword: "ส่งอีเมลรีเซ็ตรหัสผ่านไปยัง {email} หรือไม่?",
    resetPasswordSuccess: "ส่งอีเมลรีเซ็ตรหัสผ่านเรียบร้อยแล้ว",
    resetPasswordError: "เกิดข้อผิดพลาด: ",
    noUsersFound: "ไม่พบผู้ใช้ที่ตรงกับเงื่อนไข",
    refresh: "รีเฟรช",
    noLogsFound: "ไม่พบประวัติการใช้งาน",
    loading: "กำลังโหลด...",
    loadMoreLogs: "โหลดเพิ่มเติม",
    passwordPlaceholderEdit: "******** (เว้นว่างไว้หากไม่ต้องการเปลี่ยน)",
    passwordPlaceholderNew: "กำหนดรหัสผ่าน",
    passwordResetHint: "กรอกรหัสผ่านใหม่เฉพาะเมื่อต้องการเปลี่ยนเท่านั้น",

    // Publication Form
    linkProjectSourceAlert: "กรุณาเลือกโครงการต้นทาง",
    linkProjectDesc: "เชื่อมโยงผลงานกับโครงการวิจัยต้นทาง (Cross-Year Mapping)",
    currentYearNote: "ผลงานตีพิมพ์และเผยแพร่ ต้องระบุการกรอกในปีปัจจุบัน",
    noProjectsFound: "ไม่พบโครงการที่ค้นหา",
    fundedLabel: "ปีงบประมาณ: ",
    pasteLinkHint: "วางลิงก์เอกสาร (เช่น Google Drive, Dropbox หรือเว็บไซต์)",

    // Personnel Form
    fillRequiredFields: "กรุณากรอกข้อมูลให้ครบถ้วน",
    staffNamePlaceholder: "เช่น ดร.สมชาย ใจดี",
    courseNamePlaceholder: "เช่น การอบรมเชิงปฏิบัติการ...",
    urlPlaceholder: "https://drive.google.com/...",

    // Utilization Form
    enterDescriptionAlert: "กรุณาระบุรายละเอียดการนำไปใช้ประโยชน์",
    utilizationDesc: "บันทึกข้อมูลการนำผลงานวิจัยไปใช้ประโยชน์หรือสร้างผลกระทบ",
    utilDescriptionPlaceholder: "อธิบายรายละเอียดการนำไปใช้ประโยชน์...",
  }
};
